name: Bills Of Health
favicon: null
layout_spectrum: 0.6808382712770253
typography_spectrum: 0.9083799165673554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.852598762139678
  lightness: 0.536035775905475
  saturation: 0.04083581920713186
  rhythmicContrast: 0.2821017054375261
purpose: []
