name: Bills Of Health
favicon: null
layout_spectrum: 0.6808382712770253
typography_spectrum: 0.9083799165673554
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dedede'
    - '#ee963c'
    - '#3383cb'
    - '#23272a'
    - '#ce172f'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
